### ISSUE TITLE
Create a /cabbage join command that allows you to choose a colour and remembers it

### ISSUE THREAD

**Issue by sammypanda** [sammypanda/cabbage#1]
Make sure when completed to either use Closes #[issue number] in the commit, or come back to this issue to close with a list of the commits used to achieve it :heart:

**Comment by PrincessFroFr0** [comment]
Would picking a colour entail changing an aspect of the player, or creating a set of data containing which players have chosen which colours?

**Comment by sammypanda** [comment]
@PrincessFroFr0 it would probably need storage somewhere, a flat file would be okay imo

i.e. src/resources/database/teams.yml

something like that maybe, yml seems like a favorable choice for java

**Comment by sammypanda** [comment]
the '/cabbage join' & '/cabbage team' commands have been added as of 193c72d0f2938e401c70d193e3f35f9146ad651b .. no tab auto completion for the first argument (arg[0]) but that's okay

**Comment by sammypanda** [comment]
> @PrincessFroFr0 it would probably need storage somewhere, a flat file would be okay imo
> 
> i.e. src/resources/database/teams.yml
> 
> something like that maybe, yml seems like a favorable choice for java

i'm going to start working on this today

**Comment by sammypanda** [comment]
![You joined the blue team](https://user-images.githubusercontent.com/38725335/174524800-3aa63ca0-f1b1-416f-b370-377f9aa7346e.png)

![teams -> blue -> players -> sammypanda, saved to config.yml!](https://user-images.githubusercontent.com/38725335/174524727-de24a91e-5f4b-4610-b56b-7c38331f8ce0.png)

here it is as of commit 0b8917c7029fc30c8067caa84886a1174dcad887

**Comment by sammypanda** [comment]
let me know if you want something new assigned! @PrincessFroFr0
